[workspace]
resolver = "3"
members = ["crates/*"]

[workspace.package]
edition = "2024"
version = "0.1.0"
publish = false

[workspace.dependencies]
anyhow = "1"
axum = "0.8"
clap = { version = "4.6", features = ["derive", "env"] }
http = "1"
opentelemetry = "0.33"
opentelemetry-http = "0.33"
opentelemetry-otlp = "0.33"
opentelemetry_sdk = "0.33"
rand = "0.10"
redis = { version = "1.7", features = ["tokio-comp", "connection-manager"] }
reqwest = { version = "0.13", default-features = false, features = ["json"] }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
thiserror = "2"
tokio = { version = "1.53", features = ["full"] }
tracing = "0.1.44"
tracing-opentelemetry = "0.34"
tracing-subscriber = { version = "0.3.23", features = ["env-filter", "registry", "fmt", "ansi", "std"] }

telemetry = { path = "crates/telemetry" }
common = { path = "crates/common" }
